server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:8080/test_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver